<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Widgets
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

/**
 * Genesis Featured Post widget class.
 *
 * @since 0.1.8
 *
 * @package Genesis\Widgets
 */
class Explore_Marathon_Pacings_Widget extends WP_Widget {

	/**
	 * Holds widget settings defaults, populated in constructor.
	 *
	 * @var array
	 */
	protected $defaults;

	/**
	 * Constructor. Set the default widget options and create widget.
	 *
	 * @since 0.1.8
	 */
	function __construct() {

		$this->defaults = array(
			'title'                   => '',
			'headline_1_id'           => '',
			'headline_2_id'           => '',
			'headline_3_id'           => '',
			'headline_4_id'           => '',
			'headline_5_id'           => '',
			'headline_6_id'           => ''
		);

		$widget_ops = array(
			'classname'   => 'explore-marathon-pacings',
			'description' => __( 'The marathon pacing exploration widget', 'custom' ),
		);

		$control_ops = array(
			'id_base' => 'explore-marathon-pacings',
			'width'   => 505,
			'height'  => 350,
		);

		//remove_filter( 'genesis_attr_entry', 'genesis_attributes_entry' );
		//add_filter( 'genesis_attr_entry', 'custom_add_entryclasses_attr' );
		
		parent::__construct( 'explore-marathon-pacings', __( 'Flying Runner - Explore Marathon Pacings', 'custom' ), $widget_ops, $control_ops );

	}
	
	/**
	 * Echo the widget content.
	 *
	 * @since 0.1.8
	 *
	 * @param array $args Display arguments including before_title, after_title, before_widget, and after_widget.
	 * @param array $instance The settings for the particular instance of the widget
	 */
	function widget( $args, $instance ) {

		global $wp_query, $_genesis_displayed_ids;

		extract( $args );

		//* Merge with defaults
		$instance = wp_parse_args( (array) $instance, $this->defaults );

		echo $before_widget;

			
		?>
				
		<p>Explore the pacing and prediction accuracy of the 778 runners who took part in our research at London Marathon 2015.</p>
		
		<div class="wrap">
			<div id="selection-criteria" class="xone-half xfirst" >
				<div >
					<h2 style="font-size: 1em; margin-top: 0px; margin-bottom: 0.5em;">Speed</h2>
					<!--<span>I want to run the marathon in (hh:mm:ss):</span> -->

					<div>
					
						<span>Runners who finished within</span> 
						<select id="ran-within-minutes-of-this-target-time" style="width: 120px; margin-left: 0.5em; margin-right: 0.5em; padding: 4px">
							<option value="2">2 minutes</option>
							<option value="4">4 minutes</option>
							<option value="6">6 minutes</option>
							<option value="8">8 minutes</option>
							<option value="10">10 minutes</option>
							<option value="15">15 minutes</option>
							<option value="20">20 minutes</option>
							<option value="30">30 minutes</option>
							<option value="40">40 minutes</option>
						</select> 		
						<span>of this time:</span><input type="text" id="target-time" style="width: 150px; margin-left: 0.5em; padding: 4px; height: 2.5em;">
					</div>
					<div>
						<span>Runners who ran within</span> 
						<select id="ran-within-minutes-of-prediction" style="width: 120px; padding: 4px">
							<option value="2">2 minutes</option>
							<option value="4">4 minutes</option>
							<option value="6">6 minutes</option>
							<option value="8">8 minutes</option>
							<option value="10">10 minutes</option>
							<option value="15">15 minutes</option>
							<option value="20">20 minutes</option>
							<option value="30">30 minutes</option>
							<option value="40">40 minutes</option>
						</select> 		
						<span>of their predicted time</span>
					</div>
					<div style="margin-top: 0.75em;">
						<span>Runners who had previously run</span>
						<select id="previous-marathons" style="width: 150px; padding: 4px">
							<option value="Any">Any number of</option>
							<option value="0">0</option>
							<option value="1">1</option>
							<option value="2">2</option>
							<option value="3">3</option>
							<option value="3">4</option>
							<option value="3">5</option>
							<option value="6-10">6 to 10</option>
							<option value=">10">More than 10</option>
						</select> 		
						<span>marathons</span>
					</div>
					<div style="margin-top: 0.75em;">
						<span>Runners aged</span>
						<select id="age-category" style="width: 120px; padding: 4px" >
							<option value="Any" selected>Anything</option>
							<option value="18-39">18 to 39</option>
							<option value="40-49">40 to 49</option>
							<option value="50-59">50 to 59</option>
							<option value="60+">60 and over</option>
						</select> 		
					</div>
				</div>
			</div>
			<div class="xone-half" style="margin-top: 1em;">
				<input type="submit" name="predict" class="predictor-submit" id="find-runners" value="Find runners">
			</div>		

		</div>

		<!--
		<div class="wrap">
			<h2>Pacing for a <span id="pacing-target-time">????</span> marathon</h2>
			<p>These splits are based on the splits of the <span id="number-of-runners"></span> runners included in the calculations.</p> 
			<div id="number-of-runners-icons"></div>-->
			
		<!--
		</div>
		-->
		
		<div id="runners-details-intro"></div>
		<div id="sparkline-intro" style="height: 0px; visibility: collapse;">
			<p>This is the average pacing curve of all of these runners</p>
		</div>
		
		<div>
			<table>
				<tr>
					<td style="border-top: none;"><div id="sparkline"></div></td>
					<td style="border-top: none;"><input type="submit" name="" class="build-pacing" style="visibility: collapse;" id="build-pacing-average" value="Build pacing for me based on this"></td>
				</tr>
			</table>
			
		</div>
		
		<div id="runners-details" style="margin-top: 2em;"></div>
		
		<!--Hidden storage for the average splits, to use when building pacing from it-->
		<div id="splits-average-hidden" style="display: none;">
			<table style="width:100%">
			  <tr>
				<td id="5k-mean-split-s"></td>
				<td id="10k-mean-split-s"></td>
				<td id="15k-mean-split-s"></td>
				<td id="20k-mean-split-s"></td>
				<td id="25k-mean-split-s"></td>
				<td id="30k-mean-split-s"></td>
				<td id="35k-mean-split-s"></td>
				<td id="40k-mean-split-s"></td>				
			  </tr>
			</table> 
		</div>

		<div id="debug" style="background-color: #eee; display: block;">
		</div>		
		
		<?php
		echo $after_widget;

	}

	/**
	 * Update a particular instance.
	 *
	 * This function should check that $new_instance is set correctly.
	 * The newly calculated value of $instance should be returned.
	 * If "false" is returned, the instance won't be saved/updated.
	 *
	 * @since 0.1.8
	 *
	 * @param array $new_instance New settings for this instance as input by the user via form()
	 * @param array $old_instance Old settings for this instance
	 * @return array Settings to save or bool false to cancel saving
	 */
	function update( $new_instance, $old_instance ) {

		$new_instance['title']     = strip_tags( $new_instance['title'] );
		$new_instance['more_text'] = strip_tags( $new_instance['more_text'] );
		$new_instance['post_info'] = wp_kses_post( $new_instance['post_info'] );
		return $new_instance;

	}

	/**
	 * Echo the settings update form.
	 *
	 * @since 0.1.8
	 *
	 * @param array $instance Current settings
	 */
	function form( $instance ) {

		//* Merge with defaults
		$instance = wp_parse_args( (array) $instance, $this->defaults );

		?>
		
		
		<?php

	}

}
