<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Widgets
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

/**
 * Genesis Featured Post widget class.
 *
 * @since 0.1.8
 *
 * @package Genesis\Widgets
 */
class Explore_Marathon_Pacings_Widget extends WP_Widget {

	/**
	 * Holds widget settings defaults, populated in constructor.
	 *
	 * @var array
	 */
	protected $defaults;

	/**
	 * Constructor. Set the default widget options and create widget.
	 *
	 * @since 0.1.8
	 */
	function __construct() {

		$this->defaults = array(
			'title'                   => '',
			'headline_1_id'           => '',
			'headline_2_id'           => '',
			'headline_3_id'           => '',
			'headline_4_id'           => '',
			'headline_5_id'           => '',
			'headline_6_id'           => ''
		);

		$widget_ops = array(
			'classname'   => 'explore-marathon-pacings',
			'description' => __( 'The marathon pacing exploration widget', 'custom' ),
		);

		$control_ops = array(
			'id_base' => 'explore-marathon-pacings',
			'width'   => 505,
			'height'  => 350,
		);

		//remove_filter( 'genesis_attr_entry', 'genesis_attributes_entry' );
		//add_filter( 'genesis_attr_entry', 'custom_add_entryclasses_attr' );
		
		parent::__construct( 'explore-marathon-pacings', __( 'Flying Runner - Explore Marathon Pacings', 'custom' ), $widget_ops, $control_ops );

	}
	
	/**
	 * Echo the widget content.
	 *
	 * @since 0.1.8
	 *
	 * @param array $args Display arguments including before_title, after_title, before_widget, and after_widget.
	 * @param array $instance The settings for the particular instance of the widget
	 */
	function widget( $args, $instance ) {

		global $wp_query, $_genesis_displayed_ids;

		extract( $args );

		//* Merge with defaults
		$instance = wp_parse_args( (array) $instance, $this->defaults );

		echo $before_widget;

			
		?>

		<p>Explore the pacing and prediction accuracy of the 778 runners who took part in our research at London Marathon 2015.</p>
		
<!--		<div>
		<label style="display: block; margin-bottom: 0.5em;">Show me runners who finished in around this time:</label>
		<input type="text" id="target-time-h" style="width: 2em; margin-right: 0.5em; padding: 4px; height: 2.5em; text-align: center;" class="time-input input-empty" ><span style="font-size: 0.9em;">hours</span>
		<input type="text" id="target-time-m" style="width: 3em; margin-left: 0.5em; margin-right: 0.5em; padding: 4px; height: 2.5em; text-align: center;" class="time-input" value="00"><span style="font-size: 0.9em;">m</span>
		<input type="text" id="target-time-s" style="width: 3em; margin-left: 0.5em; margin-right: 0.5em; padding: 4px; height: 2.5em; text-align: center;" class="time-input" value="00"><span style="font-size: 0.9em;">s</span>
		<p id="time-validation-error" style="margin-top: 0.5em; margin-bottom: 0px; color: red; font-weight: bold; font-size: 0.9em;"></p>
		</div>-->
		<div class="wrap">
						<div id="runner-selection" class="block-group">			
                    <div class="block-group runner-selection-help">
                        <div class="block">
                            <div class="runner-selection-help-header">How to use this tool</div>
                            <div class="runner-selection-help-text">            
                                <p>To explore the prediction accuracy or pacing profile of a group of runners simply select the characteristics of the group you are interested in and click <strong>Find runners</strong>.</p>
                                <p>To build your own pacing based on any pacing profile you see, simply click the <i class="fa fa-arrow-circle-right" style="color: #666"></i> arrow to open our pacing calculator with that profile. You can customise the pacing and even print a pacing band.</p>                                
                            </div>
                        </div>
                        
                    </div>                
                    <div class="block-group runner-selection-inputs">
                        <div class="block runner-selection-label" id="label-finish-time">Finish time:</div>
                        <div class="block runner-selection-input">
                            <select id="finish-time-from">
                                <option value="7200">2 hours</option>
                                <option value="8100">2 hours 15 m</option>
                                <option value="9000">2 hours 30 m</option>
                                <option value="9900">2 hours 45 m</option>
                                <option value="10800" selected>3 hours</option>
                                <option value="11700">3 hours 15 m</option>
                                <option value="12600">3 hours 30 m</option>
                                <option value="13500">3 hours 45 m</option>
                                <option value="14400">4 hours</option>
                                <option value="15300">4 hours 15 m</option>
                                <option value="16200">4 hours 30 m</option>
                                <option value="17100">4 hours 45 m</option>
                                <option value="18000">5 hours</option>
                                <option value="19800">5 hours 30 m</option>
                                <option value="21600">6 hours</option>
                                <option value="23400">6 hours 30 m</option>
                                <option value="25200">7 hours</option>
                                <option value="27000">7 hours 30 m</option>
                            </select> 	
                            to
                            <select id="finish-time-to">
                                <option value="7200">2 hours</option>
                                <option value="8100">2 hours 15 m</option>
                                <option value="9000">2 hours 30 m</option>
                                <option value="9900">2 hours 45 m</option>
                                <option value="10800">3 hours</option>
                                <option value="11700">3 hours 15 m</option>
                                <option value="12600"selected>3 hours 30 m</option>
                                <option value="13500">3 hours 45 m</option>
                                <option value="14400">4 hours</option>
                                <option value="15300">4 hours 15 m</option>
                                <option value="16200">4 hours 30 m</option>
                                <option value="17100">4 hours 45 m</option>
                                <option value="18000">5 hours</option>
                                <option value="19800">5 hours 30 m</option>
                                <option value="21600">6 hours</option>
                                <option value="23400">6 hours 30 m</option>
                                <option value="25200">7 hours</option>
                                <option value="27000">7 hours 30 m</option>
						    </select> 	                        
                        </div>
                        
                        <div class="block runner-selection-label">Experience:</div>
                        <div class="block runner-selection-input">
                            <select id="previous-marathons">
                                <option value="Any" selected>Any number of marathons</option>
                                <option value="0">No previous marathons</option>
                                <option value="1">1 previous marathon</option>
                                <option value="2">2 previous marathons</option>
                                <option value="3">3 previous marathons</option>
                                <option value="3">4 previous marathons</option>
                                <option value="3">5 previous marathons</option>
                                <option value="6-10">6 to 10 previous marathons</option>
                                <option value=">10">More than 10 previous marathons</option>
						    </select> 
                        </div>
                        
                        <div class="block runner-selection-label">Age:</div>                    
                        <div class="block runner-selection-input">
                            <select id="age-category">
                                <option value="Any" selected>Any age</option>
                                <option value="18-39">18 to 39</option>
                                <option value="40-49">40 to 49</option>
                                <option value="50-59">50 to 59</option>
                                <option value="60+">60 and over</option>
                            </select> 		
                        </div>
                        
                        <div class="block runner-selection-label">Gender:</div>                    
                        <div class="block runner-selection-input">
                            <select id="gender">
                                <option value="Any" selected>Male and Female</option>
                                <option value="Male">Male</option>
                                <option value="Female">Female</option>
                            </select> 		
                        </div>

                        <div class="block runner-selection-label">Prediction:</div>                    
                        <div class="block runner-selection-input">
                            <select id="prediction-accuracy">
                                <option value="Any" selected>Any prediction accuracy</option>
                                <option value="99+">Extremely accurate (99% and over)</option>
                                <option value="95+">Very accurate (95% and over)</option>
                                <option value="90+">Quite accurate (90% and over)</option>
                                <option value="-90">Not very accurate (less than 90%)</option>
                            </select> 		
                        </div>
                        <div class="block find-runners-button">
                        <input type="submit" name="predict" class="predictor-submit" id="find-runners" value="Find runners">
                        </div>		
                    </div>

                    <!-- Force parent div to full height of its content -->
                    <br style="clear: both;" />
			</div>
		</div>

		<!--
		<div class="wrap">
			<h2>Pacing for a <span id="pacing-target-time">????</span> marathon</h2>
			<p>These splits are based on the splits of the <span id="number-of-runners"></span> runners included in the calculations.</p> 
			<div id="number-of-runners-icons"></div>-->
			
		<!--
		</div>
		-->
		
		<div id="runners-details-intro"></div>
		
		<div class="block-group group-charts hidden">
                <div id="" class="block group-chart-left" style="background: white;">
                    <div id="chart-group-prediction-accuracy" class="ct-chart ct-perfect-fourth">
                        <div id="chart-group-prediction-accuracy-text" style="padding-top: 140px; padding-left: 10px;">
                            <p id="chart-group-prediction-accuracy-text-title">Prediction accuracy of these runners</p>
                            <p id="prediction-accuracy-text-excellent">[NUMBER-EXCELLENT] were extremely accurate (2min @ 3 hour pace)</p>
                            <p id="prediction-accuracy-text-good">[NUMBER-GOOD] were very accurate</p>
                            <p id="prediction-accuracy-text-ok">[NUMBER-OK] were quite accurate</p>
                            <p id="prediction-accuracy-text-bad">[NUMBER-BAD] were not very accurate </p>
                        </div>
                    </div>		
                </div>
                <div id="" class="block group-chart-right" style="background: white; position: relative;">
                    <div id="sparkline-mean" style="padding-left: 10px; padding-top: 10px"></div>
                    <a id="build-pacing-button-mean" class="build-pacing-button xsmGlobalBtn" title="Open the pacing calculator with this pacing"></a>
                    <div id="chart-group-pacing-profile-text" style="padding-top: 10px; padding-left: 10px;">
                        <p id="chart-group-pacing-profile-text-title">Average pacing profile</p>
                        <p>This is the average pacing profile of all the runners in this group. Each bar represents 5km of the race. Higher bars mean longer time.</p>
                    </div>
                </div>
            </div>
		
		<!--
		<div>
			<table>
				<tr>
					<td style="border-top: none;"><div id="sparkline"></div></td>
					<td style="border-top: none;"><input type="submit" name="" class="build-pacing" style="visibility: collapse;" id="build-pacing-average" value="Build pacing for me based on this"></td>
				</tr>
			</table>
			
		</div>-->
		
		<div id="runners-details" style="margin-top: 2em;"></div>
		
		<!--Hidden storage for the average splits, to use when building pacing from it-->
		<div id="splits-average-hidden" style="display: none;">
			<table style="width:100%">
			  <tr>
				<td id="5k-mean-split-s"></td>
				<td id="10k-mean-split-s"></td>
				<td id="15k-mean-split-s"></td>
				<td id="20k-mean-split-s"></td>
				<td id="25k-mean-split-s"></td>
				<td id="30k-mean-split-s"></td>
				<td id="35k-mean-split-s"></td>
				<td id="40k-mean-split-s"></td>				
			  </tr>
			</table> 
		</div>

		<div id="debug" style="background-color: #eee; display: none;">
		</div>		
		
		<div id="prediction-accuracy-text-template" style="display: none;">
			<p id="chart-group-prediction-accuracy-text-title">Prediction accuracy of these runners</p>
			<p id="prediction-accuracy-text-excellent">[NUMBER-EXCELLENT] were extremely accurate (2min @ 3 hour pace)</p>
			<p id="prediction-accuracy-text-good">[NUMBER-GOOD] were very accurate</p>
			<p id="prediction-accuracy-text-ok">[NUMBER-OK] were quite accurate</p>
			<p id="prediction-accuracy-text-bad">[NUMBER-BAD] were not very accurate </p>
		</div>
		<div id="runner-detail-template" style="display: none;">
			<div class="runner-detail block-group">
			  <div class="runner-profile block-group">
				  <div class="block runner-image">
					  <img style="width:57px; height:auto;" src="http://images.flyingrunner.co.uk/marathon-pacing-research/[RUNNER-IMAGE]" title="[GENDER-AND-INITIALS]">
				  </div>
				  <div class="block runner-info"><strong>Age:</strong> [AGE]<br><strong>Marathons:</strong> [MARATHONS]</div>
				  <div class="block runner-accuracy-and-times">
					  <div class="block runner-accuracy">
						  <div class="runner-accuracy-circle [ACCURACY-CLASS]">
							  <div class="accuracy-percent">[ACCURACY%]</div>
							  <div class="accuracy-caption">Accurate</div>
						  </div>
					  </div>
					  <div class="block runner-times"><strong>Predicted:</strong> [PREDICTED]<br><strong>Actual:</strong> [ACTUAL]</div>
				  </div>
			  </div>
				
			  <div class="runner-pacing block-group">
				<div class="runner-chart block">
					<div id="[ID-SPARKLINE]" >
					</div>
					<a id="[ID-BUILD-PACING-BUTTON]" class="build-pacing-button" title="Open the pacing calculator with this pacing"></a>
				</div>
				<div class="runner-splits block">
					<input type="submit" name="" class="view-splits-button" id="[ID-VIEW-SPLITS-BUTTON]" value="View details..." style="display: block;" >
					<table class="splits-table hidden" id="[ID-SPLITS-TABLE]" style="display: none;">
						<tr class="splits-header">
							<td>5km</td>
							<td>10km</td>
							<td>15km</td>
							<td>20km</td>
							<td>25km</td>
							<td>30km</td>
							<td>35km</td>
							<td>40km</td>
							<td></td>
						</tr>
						<tr class="splits-time">
							<td id="td-5k-split">[SPLIT-5K]</td>
							<td id="td-10k-split">[SPLIT-10K]</td>
							<td id="td-15k-split">[SPLIT-15K]</td>
							<td id="td-20k-split">[SPLIT-20K]</td>
							<td id="td-25k-split">[SPLIT-25K]</td>
							<td id="td-30k-split">[SPLIT-30K]</td>
							<td id="td-35k-split">[SPLIT-35K]</td>
							<td id="td-40k-split">[SPLIT-40K]</td>
							<td>Time</td>
						</tr>
						<tr class="splits-pace">
							<td>[PACE-5K]</td>
							<td>[PACE-10K]</td>
							<td>[PACE-15K]</td>
							<td>[PACE-20K]</td>
							<td>[PACE-25K]</td>
							<td>[PACE-30K]</td>
							<td>[PACE-35K]</td>
							<td>[PACE-40K]</td>
							<td>Mile pace</td>                    
						</tr>
						<tr style="display: none;">
							<td id="td-finish-time-s">[FINISH-TIME-S]</td>
						</tr>
					</table>
				</div>        
			  </div>
			</div>
		</div>
		<!--Hidden div that we'll inject a tag indicating screen size in via media query in css, that we can pick up in chart buliding to ensure bars are the correct width-->
		<div id="screen-size-tag" style="display: none;"></div>
		
		<?php
		echo $after_widget;

	}

	/**
	 * Update a particular instance.
	 *
	 * This function should check that $new_instance is set correctly.
	 * The newly calculated value of $instance should be returned.
	 * If "false" is returned, the instance won't be saved/updated.
	 *
	 * @since 0.1.8
	 *
	 * @param array $new_instance New settings for this instance as input by the user via form()
	 * @param array $old_instance Old settings for this instance
	 * @return array Settings to save or bool false to cancel saving
	 */
	function update( $new_instance, $old_instance ) {

		$new_instance['title']     = strip_tags( $new_instance['title'] );
		$new_instance['more_text'] = strip_tags( $new_instance['more_text'] );
		$new_instance['post_info'] = wp_kses_post( $new_instance['post_info'] );
		return $new_instance;

	}

	/**
	 * Echo the settings update form.
	 *
	 * @since 0.1.8
	 *
	 * @param array $instance Current settings
	 */
	function form( $instance ) {

		//* Merge with defaults
		$instance = wp_parse_args( (array) $instance, $this->defaults );

		?>
		
		
		<?php

	}

}
