<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Widgets
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

/**
 * Genesis Featured Post widget class.
 *
 * @since 0.1.8
 *
 * @package Genesis\Widgets
 */
class Confirm_Personalised_Art_Print_Details_Widget extends WP_Widget {

	/**
	 * Holds widget settings defaults, populated in constructor.
	 *
	 * @var array
	 */
	protected $defaults;

	/**
	 * Constructor. Set the default widget options and create widget.
	 *
	 * @since 0.1.8
	 */
	function __construct() {

		$this->defaults = array(
		);

		$widget_ops = array(
			'classname'   => 'confirm-personalised-print-details-form',
			'description' => __( 'Personalised print details form widget', 'custom' ),
		);

		$control_ops = array(
			'id_base' => 'personalised-print-details-form',
			'width'   => 505,
			'height'  => 350,
		);

		//remove_filter( 'genesis_attr_entry', 'genesis_attributes_entry' );
		//add_filter( 'genesis_attr_entry', 'custom_add_entryclasses_attr' );
		
		parent::__construct( 'personalised-print-details-form', __( 'Flying Runner - Personalised Print Details Form', 'custom' ), $widget_ops, $control_ops );

	}
	
	/**
	 * Echo the widget content.
	 *
	 * @since 0.1.8
	 *
	 * @param array $args Display arguments including before_title, after_title, before_widget, and after_widget.
	 * @param array $instance The settings for the particular instance of the widget
	 */
	function widget( $args, $instance ) {

		global $wp_query, $_genesis_displayed_ids;

		extract( $args );

		//* Merge with defaults
		$instance = wp_parse_args( (array) $instance, $this->defaults );

		echo $before_widget;

			
		?>

<div id="intro" class="clearfix">
    
        <div class="one-half first" style="max-width: 160px;">
                        <img src="
                    <?php echo bloginfo('url') . '/wp-content/themes/lifestyle-pro/personalised-print-details/Art_print_London_road_to_jubilation_personalised.jpg'?>
                    "/>
        </div>
        <div class="one-half">
<!--            <p id="hello" style="display: none"><strong></str>Hi <span id="helloFirstName"></span>!</strong></p>-->
            <p>Thank you for ordering a personalised 'London: Road to Jubilation' art print at the London Marathon expo.</p>
            <p>We just need you to check we have your address correct and to specify the text for your print.</p>
            <!--<p>Once you've done this, we'll get it printed and dispatched to you in the next few days.</p>
            <p>If you have any problems or questions just email us at <a href="mailto:contact@flyingrunner.co.uk">contact@flyingrunner.co.uk</a></p>-->
        </div>
</div>

		<div id='findOrder'>      
            <div id='findOrderIntro'>
                <p>Please enter the postcode you gave us at the expo (so we can be sure it's you).</p>        
            </div>
            <div id='findOrderInputs'>
                <label for="findOrderPostcode">Postcode:</label>
                <input type="text" id="findOrderPostcode" value="" maxlength="16"/>
                <div id='findOrderError'></div>
                <input type="submit" id="findOrderButton" value="Find my order" />  
            </div>

            <div id='findOrderInProgress' style="display: none">
                <div id='spinner'><img src="
                    <?php echo bloginfo('url') . '/wp-content/themes/lifestyle-pro/personalised-print-details/spinner.gif'?>
                    "/>
                </div>
                <p>Finding order...</p>
            </div>

		</div>
		<div id='yourDetails' style="display: none">
            <h3>Your details</h3>            
            <p>We'll send your print to the following address.</p>
            <br>
            <p>Name: <span id="firstName"></span> <span id="lastName"></span></p>
            <p>Address: <span id="address"></span> <span id="postcode"></span></p>
            <p>Phone: <span id="phoneNumber"></span></p><br/>
            <input type="submit" id="yourDetailsBackButton" value="Back" />                  
            <input type="submit" id="yourDetailsNextButton" value="Next" />  
            <p style='margin-top: 0.5em;'>If we've got your address wrong or want us to send it somewhere else, please contact us (our contact details are below).</p>
        </div>

        <div id='printDetails'  style="display: none">
            <h3>Personalised print details</h3>
            <p>Your print can have up to 3 lines of text. Please enter the text you'd like on your print.</p>
            <p>If you have a special request for more text we'll do our best to help - please contact us.</p>
            <div>
            <img src="
                    <?php echo bloginfo('url') . '/wp-content/themes/lifestyle-pro/personalised-print-details/personalisation-closeup2.jpg'?>
                    "/>
            </div>
            <div class="">
                <label for="messageLine1">Line 1:</label>
                <input type="text" id="messageLine1" value="" maxlength="50"/>
                <label for="messageLine2">Line 2: (optional)</label>
                <input type="text" id="messageLine2" value="" maxlength="50"/>
                <label for="messageLine3">Line 3: (optional)</label>
                <input type="text" id="messageLine3" value="" maxlength="50"/>
            </div>
            <div>
                <div id='printDetailsError'></div>
                <input type="submit" id="printDetailsBackButton" value="Back" />                  
                <input type="submit" id="printDetailsNextButton" value="Next" />                  
            </div>
		</div>

        <div id='confirmDetails' style="display: none">
            <h3>Your order details</h3>
            <p>Personalised art print 'London: Road to Jubilation'</p>
            <p>Name: <span id="confirmFirstName"></span> <span id="confirmLastName"></span></p>
            <p>Address: <span id="confirmAddress"></span> <span id="confirmPostcode"></span></p>
            <p>Phone: <span id="confirmPhoneNumber"></span></p>
            <p>Text:</p>
            <p id="confirmMessageLine1"></p>
            <p id="confirmMessageLine2" style="display:none"></p>
            <p id="confirmMessageLine3" style="display:none"></p>            
            <br/>
            <p>Please check the details above are correct and then click the Submit Details button.</p>
            <div id='confirmDetailsError'></div>
            <input type="submit" id="confirmDetailsBackButton" value="Back" />                  
            <input type="submit" id="submitDetailsButton" value="Submit Details" />                  
        </div>

        <div id="orderSubmitted" style="display: none">
            <h3>Details submitted</h3>
            <p>Your details have been successfully submitted.</p>
            <p>We will dispatch your personalised 'London: Road to Jubilation' art print in the next few days.</p>
            <br>
            <p>Thank you for your order!</p>
            <p><strong>Sarah, Lin &amp; Mark</strong></p>
        </div>
        <div id='contact'>
            <p><strong>Questions or problems?</strong></p>
            <p>Just email us at <a href="mailto:contact@flyingrunner.co.uk">contact@flyingrunner.co.uk</a> or call us on 07946 918153</p>
        </div>

		<?php
		echo $after_widget;

	}

	/**
	 * Update a particular instance.
	 *
	 * This function should check that $new_instance is set correctly.
	 * The newly calculated value of $instance should be returned.
	 * If "false" is returned, the instance won't be saved/updated.
	 *
	 * @since 0.1.8
	 *
	 * @param array $new_instance New settings for this instance as input by the user via form()
	 * @param array $old_instance Old settings for this instance
	 * @return array Settings to save or bool false to cancel saving
	 */
	function update( $new_instance, $old_instance ) {

		return $new_instance;

	}

	/**
	 * Echo the settings update form.
	 *
	 * @since 0.1.8
	 *
	 * @param array $instance Current settings
	 */
	function form( $instance ) {

		//* Merge with defaults
		$instance = wp_parse_args( (array) $instance, $this->defaults );

		?>
		
		
		<?php

	}

}
