<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
echo '</div>'; //* end .site-inner or #inner

do_action( 'genesis_before_footer' );

?>
<div class="site-footer">
Copyright &#x000A9;&nbsp;2015 &middot; 
<a href="<?php echo home_url();?>">The Flying Runner</a> &middot; 
<a href="<?php echo home_url('returns');?>">Returns</a> &middot; 
<a href="<?php echo home_url('delivery');?>">Delivery Information</a> 
<br /> 
<a href="<?php echo home_url('cookies-use');?>">Cookies In Use</a> &middot; 
<a href="<?php echo home_url('privacy-policy');?>">Privacy Policy</a> &middot; 
<a href="<?php echo home_url('terms-conditions');?>">Terms and Conditions</a></div>

<?php
do_action( 'genesis_after_footer' );

echo '</div>'; //* end .site-container or #wrap

do_action( 'genesis_after' );
wp_footer(); //* we need this for plugins
?>
</body>
</html>
